// Encrypted title data
const encryptedTitle = {
    parts: [
        { text: "GEMINI", color: "text-indigo-600" },
        { text: "EDU", color: "text-fuchsia-600" },
        { text: "ID", color: "text-emerald-600" },
        { text: "CARD", color: "text-amber-600" },
        { text: "GENERATOR", color: "text-sky-600" }
    ]
};

// Country-specific data structures
const countryConfig = {
    'BD': {
        name: 'Bangladesh',
        flag: '🇧🇩',
        currency: 'BDT',
        phoneCode: '+880',
        classes: [
            'CSE','EEE','ECE','ME','CE','IT','ICT','SE','AI','DS','BBA','MBA','ACC','FIN','MKT','ECO','ENG','LAW','MED','NUR','PHARM','ARCH','STAT','MATH','PHY','CHE','BIO','SOC','PSY','GEO','HIS'
        ],
        universities: [
            // Default University
            'Dhaka International University',

            // Public Universities
            'University of Dhaka',
            'Bangladesh University of Engineering and Technology (BUET)',
            'Jahangirnagar University',
            'Rajshahi University',
            'Chittagong University',
            'Khulna University',
            'Bangladesh Agricultural University (BAU)',
            'Chittagong University of Engineering and Technology (CUET)',
            'Rajshahi University of Engineering and Technology (RUET)',
            'Khulna University of Engineering and Technology (KUET)',
            'Islamic University of Technology (IUT)',
            'Shahjalal University of Science and Technology (SUST)',
            'Bangladesh University of Professionals (BUP)',
            'Military Institute of Science and Technology (MIST)',

            // Private Universities
            'North South University (NSU)',
            'Independent University Bangladesh (IUB)',
            'BRAC University',
            'American International University Bangladesh (AIUB)',
            'East West University (EWU)',
            'United International University (UIU)',
            'Bangladesh University of Business and Technology (BUBT)',
            'Daffodil International University (DIU)'
        ],
        websites: {
            // Public Universities (Official Data)
            'University of Dhaka': 'https://www.du.ac.bd',
            'Bangladesh University of Engineering and Technology (BUET)': 'https://www.buet.ac.bd',
            'Jahangirnagar University': 'https://www.juniv.edu',
            'Rajshahi University': 'https://www.ru.ac.bd',
            'Chittagong University': 'https://www.cu.ac.bd',
            'Khulna University': 'https://ku.ac.bd',
            'Bangladesh Agricultural University (BAU)': 'https://bau.edu.bd',
            'Chittagong University of Engineering and Technology (CUET)': 'https://www.cuet.ac.bd',
            'Rajshahi University of Engineering and Technology (RUET)': 'https://www.ruet.ac.bd',
            'Khulna University of Engineering and Technology (KUET)': 'https://www.kuet.ac.bd',
            'Islamic University of Technology (IUT)': 'https://www.iutoic-dhaka.edu',
            'Shahjalal University of Science and Technology (SUST)': 'https://www.sust.edu',
            'Bangladesh University of Professionals (BUP)': 'https://www.bup.edu.bd',
            'Military Institute of Science and Technology (MIST)': 'https://www.mist.ac.bd',

            // Private Universities (Official Data)
            'North South University (NSU)': 'https://www.northsouth.edu',
            'Independent University Bangladesh (IUB)': 'https://www.iub.edu.bd',
            'BRAC University': 'https://www.bracu.ac.bd',
            'American International University Bangladesh (AIUB)': 'https://www.aiub.edu',
            'East West University (EWU)': 'https://www.ewubd.edu',
            'United International University (UIU)': 'https://www.uiu.ac.bd',
            'Bangladesh University of Business and Technology (BUBT)': 'https://www.bubt.edu.bd',
            'Daffodil International University (DIU)': 'https://www.daffodilvarsity.edu.bd',
            'Dhaka International University': 'https://www.diu.ac.bd'
        },
        addresses: {
            // Public Universities (Official Data)
            'University of Dhaka': 'Nilkhet Rd, Dhaka 1000, Bangladesh',
            'Bangladesh University of Engineering and Technology (BUET)': 'Polashi, Dhaka 1000, Bangladesh',
            'Jahangirnagar University': 'Savar, Dhaka, Bangladesh',
            'Rajshahi University': 'Motihar, Rajshahi, Bangladesh',
            'Chittagong University': 'Hathazari, Chattogram, Bangladesh',
            'Khulna University': 'Khulna, Bangladesh',
            'Bangladesh Agricultural University (BAU)': 'Mymensingh, Bangladesh',
            'Chittagong University of Engineering and Technology (CUET)': 'Raozan, Chittagong 4349, Bangladesh',
            'Rajshahi University of Engineering and Technology (RUET)': 'Kazla, Rajshahi 6204, Bangladesh',
            'Khulna University of Engineering and Technology (KUET)': 'Fulbarigate, Khulna 9203, Bangladesh',
            'Islamic University of Technology (IUT)': 'Board Bazar, Gazipur 1704, Bangladesh',
            'Shahjalal University of Science and Technology (SUST)': 'Kumargaon, Sylhet 3114, Bangladesh',
            'Bangladesh University of Professionals (BUP)': 'Mirpur Cantonment, Dhaka 1216, Bangladesh',
            'Military Institute of Science and Technology (MIST)': 'Mirpur Cantonment, Dhaka 1216, Bangladesh',

            // Private Universities (Official Data)
            'North South University (NSU)': 'Bashundhara, Dhaka, Bangladesh',
            'Independent University Bangladesh (IUB)': 'Bashundhara, Dhaka, Bangladesh',
            'BRAC University': 'Mohakhali, Dhaka, Bangladesh',
            'American International University Bangladesh (AIUB)': 'Kuratoli, Kuril, Dhaka, Bangladesh',
            'East West University (EWU)': 'Aftabnagar, Dhaka, Bangladesh',
            'United International University (UIU)': 'United City, Madani Ave, Dhaka, Bangladesh',
            'Bangladesh University of Business and Technology (BUBT)': 'Rupnagar, Mirpur 2, Dhaka, Bangladesh',
            'Daffodil International University (DIU)': 'Dhanmondi, Dhaka 1207, Bangladesh',
            'Dhaka International University': 'Satarkul, Badda, Dhaka-1212, Bangladesh'
        },
        principals: {
            'University of Dhaka': 'Prof. Md. Akhtaruzzaman',
            'Bangladesh University of Engineering and Technology (BUET)': 'Prof. Satya Majumder',
            'Chittagong University of Engineering and Technology (CUET)': 'Prof. Mohammad Alam',
            'Rajshahi University of Engineering and Technology (RUET)': 'Prof. Md. Rafiqul Sheikh',
            'Khulna University of Engineering and Technology (KUET)': 'Prof. Quazi Hossain',
            'Jahangirnagar University': 'Prof. Md. Nurul Alam',
            'Chittagong University': 'Prof. Shireen Akhter',
            'Rajshahi University': 'Prof. Golam Sattar',
            'Khulna University': 'Prof. Md. Fayek Uzzaman',
            'Islamic University of Technology (IUT)': 'Prof. Mohammad Islam',
            'Bangladesh Agricultural University (BAU)': 'Prof. Lutful Hassan',
            'Shahjalal University of Science and Technology (SUST)': 'Prof. Farid Ahmed',
            'Bangladesh University of Professionals (BUP)': 'Prof. M. Abul Mozumder',
            'Military Institute of Science and Technology (MIST)': 'Prof. Md. Shafiqul Islam',
            'North South University (NSU)': 'Prof. Atiqul Islam',
            'BRAC University': 'Prof. Vincent Chang',
            'Independent University Bangladesh (IUB)': 'Prof. Tanweer Hasan',
            'American International University Bangladesh (AIUB)': 'Prof. Carmen Lamagna',
            'East West University (EWU)': 'Prof. Mohammed Farashuddin',
            'Daffodil International University (DIU)': 'Prof. M. Lutfar Rahman',
            'Dhaka International University': 'Prof. K.M. Mohsin'
        },
        logos: {
            'Dhaka International University': 'assets/bd-logo/diu.png',
            'University of Dhaka': 'assets/bd-logo/dulogo-light_new.png',
            'Bangladesh University of Engineering and Technology (BUET)': 'assets/bd-logo/buet.png',
            'Jahangirnagar University': 'assets/bd-logo/juniv.png',
            'Rajshahi University': 'assets/bd-logo/ru-logo.png',
            'Chittagong University': 'assets/bd-logo/cu.png',
            'Khulna University': 'assets/bd-logo/ku.png',
            'Bangladesh Agricultural University (BAU)': 'assets/bd-logo/bau.png',
            'Chittagong University of Engineering and Technology (CUET)': 'assets/bd-logo/cuet.png',
            'Rajshahi University of Engineering and Technology (RUET)': 'assets/bd-logo/ruet.png',
            'Khulna University of Engineering and Technology (KUET)': 'assets/bd-logo/kuet.png',
            'Islamic University of Technology (IUT)': 'assets/bd-logo/iutoic-dhaka.png',
            'Shahjalal University of Science and Technology (SUST)': 'assets/bd-logo/sust..png',
            'Bangladesh University of Professionals (BUP)': 'assets/bd-logo/bup.png',
            'Military Institute of Science and Technology (MIST)': 'assets/bd-logo/mist.png',
            'North South University (NSU)': 'assets/bd-logo/northsouth.png',
            'Independent University Bangladesh (IUB)': 'assets/bd-logo/iub.png',
            'BRAC University': 'assets/bd-logo/bracu.png',
            'American International University Bangladesh (AIUB)': 'assets/bd-logo/aiub.png',
            'East West University (EWU)': 'assets/bd-logo/ewubd.png',
            'United International University (UIU)': 'assets/bd-logo/uiu.png',
            'Bangladesh University of Business and Technology (BUBT)': 'assets/bd-logo/bubt.png',
            'Daffodil International University (DIU)': 'assets/bd-logo/daffodilvarsity.png'
        },
        names: [
            'Ahmed Rahman',
            'Mohammad Ali',
            'Hasan Mahmud',
            'Rashid Khan',
            'Karim Uddin',
            'Nurul Islam',
            'Abdul Gafur',
            'Shahid Hasan',
            'Rafiq Ahmed',
            'Jahangir Alam',
            'Kamrul Hossain',
            'Sakib Hasan',
            'Rakib Ahmed',
            'Nazmul Islam',
            'Sajib Rahman',
            'Tareq Hasan',
            'Arif Khan',
            'Sabbir Ahmed',
            'Rifat Islam',
            'Nayeem Uddin',
            'Mahbub Alam',
            'Shahriar Ahmed',
            'Faisal Rahman',
            'Imran Khan',
            'Sajjad Hossain',
            'Mizanur Rahman',
            'Ashraf Uddin',
            'Farid Ahmed',
            'Jalal Uddin',
            'Bashir Ahmed',
            'Nasir Uddin',
            'Khalil Rahman',
            'Momin Uddin',
            'Siraj Uddin',
            'Azizur Rahman',
            'Mofiz Uddin',
            'Rashid Uddin',
            'Jahid Hasan',
            'Mamun Ahmed',
            'Rony Khan'
        ],
        addresses: [
            'Dhanmondi, Dhaka 1205, Bangladesh',
            'Gulshan, Dhaka 1212, Bangladesh',
            'Uttara, Dhaka 1230, Bangladesh',
            'Banani, Dhaka 1213, Bangladesh',
            'Motijheel, Dhaka 1000, Bangladesh',
            'Wari, Dhaka 1203, Bangladesh',
            'Ramna, Dhaka 1000, Bangladesh',
            'Tejgaon, Dhaka 1215, Bangladesh',
            'Mohammadpur, Dhaka 1207, Bangladesh',
            'Lalmatia, Dhaka 1207, Bangladesh',
            'Chittagong, Bangladesh',
            'Rajshahi, Bangladesh',
            'Khulna, Bangladesh',
            'Sylhet, Bangladesh',
            'Barisal, Bangladesh',
            'Rangpur, Bangladesh',
            'Mymensingh, Bangladesh',
            'Comilla, Bangladesh',
            'Jessore, Bangladesh',
            'Narayanganj, Bangladesh',
            'Gazipur, Bangladesh',
            'Bogra, Bangladesh',
            'Dinajpur, Bangladesh',
            'Cox\'s Bazar, Bangladesh',
            'Chandpur, Bangladesh',
            'Kushtia, Bangladesh',
            'Pabna, Bangladesh',
            'Noakhali, Bangladesh',
            'Feni, Bangladesh',
            'Lakshmipur, Bangladesh'
        ]
    },
    'IN': {
        name: 'India',
        flag: '🇮🇳',
        currency: 'INR',
        phoneCode: '+91',
        classes: [
            'CSE','IT','ECE','EEE','ME','CE','AIML','DS','CIV','CHE','BBA','MBA','B.COM','M.COM','BSC','MSC','ENG','LAW','MBBS','BDS','BPHARM','ARCH','STAT','MATH','PHY','CHE','BIO'
        ],
        universities: [
            'Guru Gobind Singh Indraprastha University',
            'University of Delhi',
            'Jawaharlal Nehru University',
            'Panjab University, Chandigarh',
            'University of Mumbai',
            'Savitribai Phule Pune University',
            'Banaras Hindu University',
            'University of Calcutta',
            'Anna University',
            'University of Hyderabad'
        ],
        websites: {
            'Guru Gobind Singh Indraprastha University': 'https://www.ipu.ac.in',
            'University of Delhi': 'https://www.du.ac.in',
            'Jawaharlal Nehru University': 'https://www.jnu.ac.in',
            'Panjab University, Chandigarh': 'https://puchd.ac.in',
            'University of Mumbai': 'https://mu.ac.in',
            'Savitribai Phule Pune University': 'https://www.unipune.ac.in',
            'Banaras Hindu University': 'https://www.bhu.ac.in',
            'University of Calcutta': 'https://www.caluniv.ac.in',
            'Anna University': 'https://www.annauniv.edu',
            'University of Hyderabad': 'https://uohyd.ac.in'
        },
        addresses: {
            'Guru Gobind Singh Indraprastha University': 'Sector 16C, Dwarka, New Delhi, Delhi 110078',
            'University of Delhi': 'Benito Juarez Marg, South Campus, New Delhi, Delhi 110021',
            'Jawaharlal Nehru University': 'New Mehrauli Road, JNU, New Delhi, Delhi 110067',
            'Panjab University, Chandigarh': 'Sector 14, Chandigarh, 160014',
            'University of Mumbai': 'M.G. Road, Fort, Mumbai, Maharashtra 400032',
            'Savitribai Phule Pune University': 'Ganeshkhind, Pune, Maharashtra 411007',
            'Banaras Hindu University': 'Ajagara, Varanasi, Uttar Pradesh 221005',
            'University of Calcutta': '87/1, College Street, Kolkata, West Bengal 700073',
            'Anna University': 'Sardar Patel Rd, Guindy, Chennai, Tamil Nadu 600025',
            'University of Hyderabad': 'Prof. C.R. Rao Road, Gachibowli, Hyderabad, Telangana 500046'
        },
        principals: {
            'Guru Gobind Singh Indraprastha University': 'Prof. Mahesh Verma',
            'University of Delhi': 'Prof. Yogesh Singh',
            'Jawaharlal Nehru University': 'Prof. Santishree Pandit',
            'Panjab University, Chandigarh': 'Prof. Raj Kumar',
            'University of Mumbai': 'Prof. Suhas Pednekar',
            'Savitribai Phule Pune University': 'Prof. Nitin Karmalkar',
            'Banaras Hindu University': 'Prof. Sudhir Jain',
            'University of Calcutta': 'Prof. Sonali Banerjee',
            'Anna University': 'Prof. R. Velraj',
            'University of Hyderabad': 'Prof. B.J. Rao'
        },
        names: [
            'Rohan Sharma',
            'Siddharth Patel',
            'Aditya Singh',
            'Arjun Gupta',
            'Dhruv Kumar',
            'Kabir Khan',
            'Aryan Verma',
            'Vihaan Jain',
            'Ishaan Reddy',
            'Dev Joshi',
            'Krishnan Iyer',
            'Neel Mehta',
            'Aarav Das',
            'Vivaan Singh',
            'Reyansh Chaudhary',
            'Samar Arora',
            'Yash Yadav',
            'Kunal Desai',
            'Anand Sharma',
            'Gautam Mishra'
        ],
        addresses: [
            'At- Sadanandpur Dist- Supaul, Bihar',
            '123 Main St, Anytown, USA',
            '456 College Rd, Cityville, State',
            '789 Academic Ave, Metropoli, Country'
        ]
    },
    'PK': {
        name: 'Pakistan',
        flag: '🇵🇰',
        currency: 'PKR',
        phoneCode: '+92',
        classes: [
            'CSE','EEE','ECE','ME','CE','IT','ICT','SE','AI','DS','BBA','MBA','ACC','FIN','MKT','ECO','ENG','LAW','MBBS','PHARM','ARCH','STAT','MATH','PHY','CHE','BIO'
        ],
        universities: [
            'University of the Punjab',
            'National University of Sciences and Technology (NUST)',
            'Quaid-i-Azam University (QAU)',
            'University of Karachi',
            'University of Engineering and Technology, Lahore (UET Lahore)',
            'COMSATS University Islamabad',
            'Allama Iqbal Open University (AIOU)',
            'University of Peshawar',
            'Bahauddin Zakariya University (BZU)',
            'Government College University, Lahore (GCU Lahore)',
            'Pakistan Institute of Engineering and Applied Sciences (PIEAS)',
            'National Textile University (NTU)',
            'University of Sargodha (UOS)',
            'Institute of Space Technology (IST)',
            'Lahore University of Management Sciences (LUMS)',
            'Aga Khan University (AKU)',
            'Institute of Business Administration, Karachi (IBA)',
            'University of Lahore (UOL)',
            'Hamdard University',
            'Bahria University',
            'Iqra University',
            'Riphah International University',
            'National University of Computer and Emerging Sciences (FAST-NUCES)'
        ],
        websites: {
            'University of the Punjab': 'https://pu.edu.pk',
            'National University of Sciences and Technology (NUST)': 'https://nust.edu.pk',
            'Quaid-i-Azam University (QAU)': 'https://qau.edu.pk',
            'University of Karachi': 'https://uok.edu.pk',
            'University of Engineering and Technology, Lahore (UET Lahore)': 'https://uet.edu.pk',
            'COMSATS University Islamabad': 'https://comsats.edu.pk',
            'Allama Iqbal Open University (AIOU)': 'https://aiou.edu.pk',
            'University of Peshawar': 'https://uop.edu.pk',
            'Bahauddin Zakariya University (BZU)': 'https://bzu.edu.pk',
            'Government College University, Lahore (GCU Lahore)': 'https://gcu.edu.pk',
            'Pakistan Institute of Engineering and Applied Sciences (PIEAS)': 'https://pieas.edu.pk',
            'National Textile University (NTU)': 'https://ntu.edu.pk',
            'University of Sargodha (UOS)': 'https://uos.edu.pk',
            'Institute of Space Technology (IST)': 'https://ist.edu.pk',
            'Lahore University of Management Sciences (LUMS)': 'https://lums.edu.pk',
            'Aga Khan University (AKU)': 'https://aku.edu',
            'Institute of Business Administration, Karachi (IBA)': 'https://iba.edu.pk',
            'University of Lahore (UOL)': 'https://uol.edu.pk',
            'Hamdard University': 'https://hamdard.edu.pk',
            'Bahria University': 'https://bahria.edu.pk',
            'Iqra University': 'https://iqra.edu.pk',
            'Riphah International University': 'https://riphah.edu.pk',
            'National University of Computer and Emerging Sciences (FAST-NUCES)': 'https://nu.edu.pk'
        },
        addresses: {
            'University of the Punjab': 'Quaid-e-Azam Campus, Canal Rd, Lahore, Punjab, Pakistan',
            'National University of Sciences and Technology (NUST)': 'H-12 Campus, Islamabad, Pakistan',
            'Quaid-i-Azam University (QAU)': 'Shahdara Valley Rd, Islamabad, Pakistan',
            'University of Karachi': 'Main University Rd, Karachi, Sindh, Pakistan',
            'University of Engineering and Technology, Lahore (UET Lahore)': 'GT Rd, Lahore 54890, Punjab, Pakistan',
            'COMSATS University Islamabad': 'Park Rd, Tarlai Kalan, Islamabad, Pakistan',
            'Allama Iqbal Open University (AIOU)': 'H-8/2, Islamabad, Pakistan',
            'University of Peshawar': 'University Rd, Peshawar, Khyber Pakhtunkhwa, Pakistan',
            'Bahauddin Zakariya University (BZU)': 'BZU, Multan, Punjab, Pakistan',
            'Government College University, Lahore (GCU Lahore)': 'Katchery Rd, Lahore, Punjab, Pakistan',
            'Pakistan Institute of Engineering and Applied Sciences (PIEAS)': 'Lehtrar Rd, Nilore, Islamabad, Pakistan',
            'National Textile University (NTU)': 'Sheikhupura Rd, Faisalabad, Punjab, Pakistan',
            'University of Sargodha (UOS)': 'University Rd, Sargodha, Punjab, Pakistan',
            'Institute of Space Technology (IST)': 'Islamabad Highway, Islamabad, Pakistan',
            'Lahore University of Management Sciences (LUMS)': 'Sector U, DHA, Lahore, Punjab, Pakistan',
            'Aga Khan University (AKU)': 'Stadium Rd, Karachi, Sindh, Pakistan',
            'Institute of Business Administration, Karachi (IBA)': 'University Rd, Karachi, Sindh, Pakistan',
            'University of Lahore (UOL)': '1-KM Defence Rd, Lahore, Punjab, Pakistan',
            'Hamdard University': 'Madinat al-Hikmah, Karachi, Sindh, Pakistan',
            'Bahria University': 'Shangrilla Rd, E-8, Islamabad, Pakistan',
            'Iqra University': 'Main Campus, Karachi, Sindh, Pakistan',
            'Riphah International University': 'I-14 Campus, Islamabad, Pakistan',
            'National University of Computer and Emerging Sciences (FAST-NUCES)': 'A.K. Brohi Rd, H-11/4, Islamabad, Pakistan'
        },
        principals: {
            'University of the Punjab': 'Prof. Niaz Ahmad',
            'National University of Sciences and Technology (NUST)': 'Lt Gen Javed Bukhari',
            'Quaid-i-Azam University (QAU)': 'Prof. Muhammad Ali',
            'University of Karachi': 'Prof. Khalid Iraqi',
            'University of Engineering and Technology, Lahore (UET Lahore)': 'Prof. Mansoor Sarwar',
            'COMSATS University Islamabad': 'Prof. Muhammad Afzal',
            'Allama Iqbal Open University (AIOU)': 'Prof. Zia Ul-Qayyum',
            'University of Peshawar': 'Prof. Muhammad Khan',
            'Bahauddin Zakariya University (BZU)': 'Prof. Mansoor Kundi',
            'Government College University, Lahore (GCU Lahore)': 'Prof. Asghar Zaidi',
            'Pakistan Institute of Engineering and Applied Sciences (PIEAS)': 'Prof. Nasir Mirza',
            'National Textile University (NTU)': 'Prof. Tanveer Hussain',
            'University of Sargodha (UOS)': 'Prof. Qaisar Abbas',
            'Institute of Space Technology (IST)': 'Prof. Muhammad Shafique',
            'Lahore University of Management Sciences (LUMS)': 'Dr. Arshad Ahmad',
            'Aga Khan University (AKU)': 'Dr. Sulaiman Shahabuddin',
            'Institute of Business Administration, Karachi (IBA)': 'Dr. S Akbar Zaidi',
            'University of Lahore (UOL)': 'Prof. Muhammad Ashraf',
            'Hamdard University': 'Prof. Syed Rashid',
            'Bahria University': 'Vice Admiral Muhammad Shafiq',
            'Iqra University': 'Prof. Wasim Qazi',
            'Riphah International University': 'Prof. Anis Ahmad',
            'National University of Computer and Emerging Sciences (FAST-NUCES)': 'Prof. Amir Muhammad'
        },
        logos: {
            'University of the Punjab': 'assets/pk-logo/pu.png',
            'National University of Sciences and Technology (NUST)': 'assets/pk-logo/nust.png',
            'Quaid-i-Azam University (QAU)': 'assets/pk-logo/qau.png',
            'University of Karachi': 'assets/pk-logo/uok.png',
            'University of Engineering and Technology, Lahore (UET Lahore)': 'assets/pk-logo/uet.png',
            'COMSATS University Islamabad': 'assets/pk-logo/comsats.png',
            'Allama Iqbal Open University (AIOU)': 'assets/pk-logo/aiou.png',
            'University of Peshawar': 'assets/pk-logo/uop.png',
            'Bahauddin Zakariya University (BZU)': 'assets/pk-logo/bzu.png',
            'Government College University, Lahore (GCU Lahore)': 'assets/pk-logo/gcu.png',
            'Pakistan Institute of Engineering and Applied Sciences (PIEAS)': 'assets/pk-logo/pieas.png',
            'National Textile University (NTU)': 'assets/pk-logo/ntu.png',
            'University of Sargodha (UOS)': 'assets/pk-logo/uos.png',
            'Institute of Space Technology (IST)': 'assets/pk-logo/ist.png',
            'Lahore University of Management Sciences (LUMS)': 'assets/pk-logo/LUMS Logo.png',
            'Aga Khan University (AKU)': 'assets/pk-logo/AKU_logo.png',
            'Institute of Business Administration, Karachi (IBA)': 'assets/pk-logo/iba.png',
            'University of Lahore (UOL)': 'assets/pk-logo/uol.png',
            'Hamdard University': 'assets/pk-logo/hamdard.png',
            'Bahria University': 'assets/pk-logo/bahria.png',
            'Iqra University': 'assets/pk-logo/iqra.png',
            'Riphah International University': 'assets/pk-logo/riphah-logo.svg',
            'National University of Computer and Emerging Sciences (FAST-NUCES)': 'assets/pk-logo/NU-logo.png'
        },
        names: [
            'Ali Khan','Ayesha Siddiqui','Ahmed Raza','Fatima Noor','Usman Ali','Maryam Sheikh','Zain Abbas','Hira Khan','Bilal Ahmed','Laiba Iqbal','Hamza Saeed','Zoya Khan','Imran Shah','Aqsa Fatima','Salman Rafiq','Maira Ali'
        ]
    },
    'UK': {
        name: 'United Kingdom',
        flag: '🇬🇧',
        currency: 'GBP',
        phoneCode: '+44',
        classes: [
            'CSE','EEE','ECE','ME','CE','IT','ICT','SE','AI','DS','BBA','MBA','ACC','FIN','MKT','ECO','ENG','LAW','MED','NUR','PHARM','ARCH','STAT','MATH','PHY','CHE','BIO'
        ],
        universities: [
            // Default University (first)
            'University of the Pacific',
            'University of Oxford',
            'University of Cambridge',
            'Imperial College London',
            'London School of Economics (LSE)',
            'University College London (UCL)',
            'University of Edinburgh',
            'King’s College London',
            'University of Manchester',
            'University of Bristol',
            'University of Glasgow',
            'University of Birmingham',
            'University of Leeds',
            'University of Warwick',
            'University of Sheffield',
            'University of Southampton',
            'University of York',
            'University of Liverpool',
            'University of Nottingham',
            'University of St Andrews',
            'Queen Mary University of London'
        ],
        websites: {
            'University of Oxford': 'https://www.ox.ac.uk',
            'University of Cambridge': 'https://www.cam.ac.uk',
            'Imperial College London': 'https://www.imperial.ac.uk',
            'London School of Economics (LSE)': 'https://www.lse.ac.uk',
            'University College London (UCL)': 'https://www.ucl.ac.uk',
            'University of Edinburgh': 'https://www.ed.ac.uk',
            'King’s College London': 'https://www.kcl.ac.uk',
            'University of Manchester': 'https://www.manchester.ac.uk',
            'University of Bristol': 'https://www.bristol.ac.uk',
            'University of Glasgow': 'https://www.gla.ac.uk',
            'University of Birmingham': 'https://www.birmingham.ac.uk',
            'University of Leeds': 'https://www.leeds.ac.uk',
            'University of Warwick': 'https://warwick.ac.uk',
            'University of Sheffield': 'https://www.sheffield.ac.uk',
            'University of Southampton': 'https://www.southampton.ac.uk',
            'University of York': 'https://www.york.ac.uk',
            'University of Liverpool': 'https://www.liverpool.ac.uk',
            'University of Nottingham': 'https://www.nottingham.ac.uk',
            'University of St Andrews': 'https://www.st-andrews.ac.uk',
            'Queen Mary University of London': 'https://www.qmul.ac.uk',
            'University of the Pacific': 'https://www.pacific.edu'
        },
        addresses: {
            'University of Oxford': 'Wellington Square, Oxford, UK',
            'University of Cambridge': 'Trinity Ln, Cambridge, UK',
            'Imperial College London': 'South Kensington, London, UK',
            'London School of Economics (LSE)': 'Houghton St, London, UK',
            'University College London (UCL)': 'Gower St, London, UK',
            'University of Edinburgh': 'South Bridge, Edinburgh, UK',
            'King’s College London': 'Strand, London, UK',
            'University of Manchester': 'Oxford Rd, Manchester, UK',
            'University of Bristol': 'Tyndall Ave, Bristol, UK',
            'University of Glasgow': 'University Ave, Glasgow, UK',
            'University of Birmingham': 'Edgbaston, Birmingham, UK',
            'University of Leeds': 'Woodhouse Ln, Leeds, UK',
            'University of Warwick': 'Coventry, UK',
            'University of Sheffield': 'Western Bank, Sheffield, UK',
            'University of Southampton': 'University Rd, Southampton, UK',
            'University of York': 'Heslington, York, UK',
            'University of Liverpool': 'Liverpool, UK',
            'University of Nottingham': 'University Park, Nottingham, UK',
            'University of St Andrews': 'St Andrews, Scotland, UK',
            'Queen Mary University of London': 'Mile End Rd, London, UK',
            'University of the Pacific': '3601 Pacific Ave, Stockton, CA, USA'
        },
        principals: {
            'University of Oxford': 'Prof. Louise Richardson',
            'University of Cambridge': 'Prof. Stephen Toope',
            'Imperial College London': 'Prof. Alice Gast',
            'London School of Economics (LSE)': 'Prof. Minouche Shafik',
            'University College London (UCL)': 'Prof. Michael Spence',
            'University of Edinburgh': 'Prof. Peter Mathieson',
            'King\'s College London': 'Prof. Shitij Kapur',
            'University of Manchester': 'Prof. Nancy Rothwell',
            'University of Bristol': 'Prof. Hugh Brady',
            'University of Glasgow': 'Prof. Anton Muscatelli',
            'University of Birmingham': 'Prof. David Eastwood',
            'University of Leeds': 'Prof. Simone Buitendijk',
            'University of Warwick': 'Prof. Stuart Croft',
            'University of Sheffield': 'Prof. Koen Lamberts',
            'University of Southampton': 'Prof. Mark Smith',
            'University of York': 'Prof. Charlie Jeffery',
            'University of Liverpool': 'Prof. Janet Beer',
            'University of Nottingham': 'Prof. Shearer West',
            'University of St Andrews': 'Prof. Sally Mapstone',
            'Queen Mary University of London': 'Prof. Colin Bailey',
            'University of the Pacific': 'Dr. Christopher Callahan'
        },
        logos: {
            'University of Oxford': 'assets/uk-logo/ox.png',
            'University of Cambridge': 'assets/uk-logo/ac.png',
            'Imperial College London': 'assets/uk-logo/imperial.png',
            'London School of Economics (LSE)': 'assets/uk-logo/imperial.png',
            'University College London (UCL)': 'assets/uk-logo/ucl.png',
            'University of Edinburgh': 'assets/uk-logo/ox.png',
            'King’s College London': 'assets/uk-logo/kcl.png',
            'University of Manchester': 'assets/uk-logo/manchester.ico',
            'University of Bristol': 'assets/uk-logo/bristol.png',
            'University of Glasgow': 'assets/uk-logo/gla.png',
            'University of Birmingham': 'assets/uk-logo/birmingham.png',
            'University of Leeds': 'assets/uk-logo/leeds.png',
            'University of Warwick': 'assets/uk-logo/warwick.PNG',
            'University of Sheffield': 'assets/uk-logo/sheffield.png',
            'University of Southampton': 'assets/uk-logo/ox.png',
            'University of York': 'assets/uk-logo/york.png',
            'University of Liverpool': 'assets/uk-logo/liverpool.png',
            'University of Nottingham': 'assets/uk-logo/nottingham.png',
            'University of St Andrews': 'assets/uk-logo/st-andrews.png',
            'Queen Mary University of London': 'assets/uk-logo/qmul.png',
            'University of the Pacific': 'assets/uk-logo/pacific.png'
        },
        names: ['Oliver Smith','Amelia Johnson','George Brown','Isla Jones','Harry Williams','Emily Taylor']
    },
    'NG': {
        name: 'Nigeria',
        flag: '🇳🇬',
        currency: 'NGN',
        phoneCode: '+234',
        classes: [
            'CSE','EEE','ECE','ME','CE','IT','ICT','SE','AI','DS','BBA','MBA','ACC','FIN','MKT','ECO','ENG','LAW','MBBS','PHARM','ARCH','STAT','MATH','PHY','CHE','BIO','AGR','VET','EDU','SOC','PSY','POL','HIS','LIT','MUS','ART'
        ],
        universities: [
            'University of Ibadan',
            'University of Lagos',
            'Obafemi Awolowo University',
            'Ahmadu Bello University',
            'University of Nigeria, Nsukka',
            'University of Ilorin',
            'Federal University of Technology Akure',
            'University of Benin',
            'Covenant University',
            'Lagos State University',
            'University of Jos',
            'Bayero University Kano',
            'Federal University of Technology Minna',
            'University of Port Harcourt',
            'Nnamdi Azikiwe University',
            'Adekunle Ajasin University',
            'University of Agriculture Abeokuta',
            'Babcock University',
            'Redeemer\'s University Nigeria',
            'Pan-Atlantic University'
        ],
        websites: {
            'University of Ibadan': 'https://www.ui.edu.ng',
            'University of Lagos': 'https://www.unilag.edu.ng',
            'Obafemi Awolowo University': 'https://www.oauife.edu.ng',
            'Ahmadu Bello University': 'https://www.abu.edu.ng',
            'University of Nigeria, Nsukka': 'https://www.unn.edu.ng',
            'University of Ilorin': 'https://www.unilorin.edu.ng',
            'Federal University of Technology Akure': 'https://www.futa.edu.ng',
            'University of Benin': 'https://www.uniben.edu',
            'Covenant University': 'https://www.covenantuniversity.edu.ng',
            'Lagos State University': 'https://www.lasu.edu.ng',
            'University of Jos': 'https://www.unijos.edu.ng',
            'Bayero University Kano': 'https://www.buk.edu.ng',
            'Federal University of Technology Minna': 'https://www.futminna.edu.ng',
            'University of Port Harcourt': 'https://www.uniport.edu.ng',
            'Nnamdi Azikiwe University': 'https://www.unizik.edu.ng',
            'Adekunle Ajasin University': 'https://www.aaua.edu.ng',
            'University of Agriculture Abeokuta': 'https://www.unaab.edu.ng',
            'Babcock University': 'https://www.babcock.edu.ng',
            'Redeemer\'s University Nigeria': 'https://www.run.edu.ng',
            'Pan-Atlantic University': 'https://www.pau.edu.ng'
        },
        addresses: {
            'University of Ibadan': 'Ibadan, Oyo State, Nigeria',
            'University of Lagos': 'Lagos, Nigeria',
            'Obafemi Awolowo University': 'Ile-Ife, Osun State, Nigeria',
            'Ahmadu Bello University': 'Zaria, Kaduna State, Nigeria',
            'University of Nigeria, Nsukka': 'Nsukka, Enugu State, Nigeria',
            'University of Ilorin': 'Ilorin, Kwara State, Nigeria',
            'Federal University of Technology Akure': 'Akure, Ondo State, Nigeria',
            'University of Benin': 'Benin City, Edo State, Nigeria',
            'Covenant University': 'Ota, Ogun State, Nigeria',
            'Lagos State University': 'Ojo, Lagos, Nigeria',
            'University of Jos': 'Jos, Plateau State, Nigeria',
            'Bayero University Kano': 'Kano, Nigeria',
            'Federal University of Technology Minna': 'Minna, Niger State, Nigeria',
            'University of Port Harcourt': 'Port Harcourt, Rivers State, Nigeria',
            'Nnamdi Azikiwe University': 'Awka, Anambra State, Nigeria',
            'Adekunle Ajasin University': 'Akungba, Ondo State, Nigeria',
            'University of Agriculture Abeokuta': 'Abeokuta, Ogun State, Nigeria',
            'Babcock University': 'Ilishan-Remo, Ogun State, Nigeria',
            'Redeemer\'s University Nigeria': 'Ede, Osun State, Nigeria',
            'Pan-Atlantic University': 'Lekki, Lagos, Nigeria'
        },
        principals: {
            'University of Ibadan': 'Prof. Kayode Adebowale',
            'University of Lagos': 'Prof. Folasade Ogunsola',
            'Obafemi Awolowo University': 'Prof. Simeon Bamire',
            'Ahmadu Bello University': 'Prof. Kabiru Bala',
            'University of Nigeria, Nsukka': 'Prof. Charles Igwe',
            'University of Ilorin': 'Prof. Wahab Egbewole',
            'Federal University of Technology Akure': 'Prof. Adenike Oladiji',
            'University of Benin': 'Prof. Lilian Salami',
            'Covenant University': 'Prof. Abiodun Adebayo',
            'Lagos State University': 'Prof. Ibiyemi Olatunji-Bello',
            'University of Jos': 'Prof. Tanko Ishaya',
            'Bayero University Kano': 'Prof. Sagir Abbas',
            'Federal University of Technology Minna': 'Prof. Faruk Adamu',
            'University of Port Harcourt': 'Prof. Owunari Georgewill',
            'Nnamdi Azikiwe University': 'Prof. Charles Esimone',
            'Adekunle Ajasin University': 'Prof. Olugbenga Ige',
            'University of Agriculture Abeokuta': 'Prof. Kolawole Salako',
            'Babcock University': 'Prof. Ademola Tayo',
            'Redeemer\'s University Nigeria': 'Prof. Anthony Akinlo',
            'Pan-Atlantic University': 'Prof. Enase Okonedo'
        },
        names: [
            'Adebayo Ogunlesi', 'Chinwe Okonkwo', 'Emeka Nwosu', 'Fatima Ibrahim', 'Gabriel Adebayo', 'Hauwa Mohammed', 'Ibrahim Tanko', 'Joyce Okafor', 'Kemi Adeyemi', 'Ladi Bello', 'Musa Garba', 'Ngozi Okwu', 'Oluwaseun Adebayo', 'Patience Musa', 'Quadri Olanrewaju', 'Ruth Okonkwo', 'Samuel Adeyemi', 'Temitope Ogunlesi', 'Uche Nwankwo', 'Victoria Okafor'
        ],
        logos: {
            'University of Ibadan': 'assets/ng-logo/ui.png',
            'University of Lagos': 'assets/ng-logo/unilag.png',
            'Obafemi Awolowo University': 'assets/ng-logo/oauife.png',
            'Ahmadu Bello University': 'assets/ng-logo/abu.png',
            'University of Nigeria, Nsukka': 'assets/ng-logo/unn.png',
            'University of Ilorin': 'assets/ng-logo/unilorin.png',
            'Federal University of Technology Akure': 'assets/ng-logo/futa.png',
            'University of Benin': 'assets/ng-logo/uniben.png',
            'Covenant University': 'assets/ng-logo/covenantuniversity.png',
            'Lagos State University': 'assets/ng-logo/lasu.png',
            'University of Jos': 'assets/ng-logo/unijos.png',
            'Bayero University Kano': 'assets/ng-logo/buk.png',
            'Federal University of Technology Minna': 'assets/ng-logo/futminna.png',
            'University of Port Harcourt': 'assets/ng-logo/uniport.png',
            'Nnamdi Azikiwe University': 'assets/ng-logo/unizik.png',
            'Adekunle Ajasin University': 'assets/ng-logo/aaua.png',
            'University of Agriculture Abeokuta': 'assets/ng-logo/funaab.png',
            'Babcock University': 'assets/ng-logo/babcock.png',
            'Redeemer\'s University Nigeria': 'assets/ng-logo/run.png',
            'Pan-Atlantic University': 'assets/ng-logo/pau.png'
        }
    },
    'AU': {
        name: 'Australia',
        flag: '🇦🇺',
        currency: 'AUD',
        phoneCode: '+61',
        classes: [
            'CSE','EEE','ECE','ME','CE','IT','ICT','SE','AI','DS','BBA','MBA','ACC','FIN','MKT','ECO','ENG','LAW','MED','NUR','PHARM','ARCH','STAT','MATH','PHY','CHE','BIO','AGR','VET','EDU','SOC','PSY','POL','HIS','LIT','MUS','ART'
        ],
        universities: [
            'The Australian National University',
            'The University of Sydney',
            'Monash University',
            'The University of Melbourne',
            'The University of Queensland',
            'University of New South Wales',
            'University of Western Australia',
            'University of Adelaide',
            'University of Technology Sydney',
            'Curtin University'
        ],
        websites: {
            'The University of Sydney': 'https://www.sydney.edu.au',
            'Monash University': 'https://www.monash.edu',
            'The Australian National University': 'https://www.anu.edu.au',
            'The University of Melbourne': 'https://www.unimelb.edu.au',
            'The University of Queensland': 'https://www.uq.edu.au',
            'University of New South Wales': 'https://www.unsw.edu.au',
            'University of Western Australia': 'https://www.uwa.edu.au',
            'University of Adelaide': 'https://www.adelaide.edu.au',
            'University of Technology Sydney': 'https://www.uts.edu.au',
            'Curtin University': 'https://www.curtin.edu.au'
        },
        addresses: {
            'The University of Sydney': 'Sydney, NSW',
            'Monash University': 'Melbourne, VIC',
            'The Australian National University': 'Canberra, ACT',
            'The University of Melbourne': 'Melbourne, VIC',
            'The University of Queensland': 'Brisbane, QLD',
            'University of New South Wales': 'Sydney, NSW',
            'University of Western Australia': 'Perth, WA',
            'University of Adelaide': 'Adelaide, SA',
            'University of Technology Sydney': 'Sydney, NSW',
            'Curtin University': 'Perth, WA'
        },
        principals: {
            'The University of Sydney': 'Prof. Mark Scott',
            'Monash University': 'Prof. Margaret Gardner',
            'The Australian National University': 'Prof. Brian Schmidt',
            'The University of Melbourne': 'Prof. Duncan Maskell',
            'The University of Queensland': 'Prof. Deborah Terry',
            'University of New South Wales': 'Prof. Attila Brungs',
            'University of Western Australia': 'Prof. Amit Chakma',
            'University of Adelaide': 'Prof. Peter Høj',
            'University of Technology Sydney': 'Prof. Andrew Parfitt',
            'Curtin University': 'Prof. Harlene Hayne'
        },
        names: [
            'James Mitchell', 'Sarah Thompson', 'Michael Chen', 'Emma Wilson', 'David Brown', 'Jessica Lee', 'Christopher Taylor', 'Amanda Davis', 'Matthew Anderson', 'Rebecca White', 'Daniel Johnson', 'Sophie Martin', 'Andrew Clark', 'Olivia Green', 'Benjamin Hall', 'Charlotte King', 'Samuel Wright', 'Isabella Young', 'William Turner', 'Grace Parker'
        ],
        logos: {
            'The University of Sydney': 'assets/🇦🇺-logo/sydney.png',
            'Monash University': 'assets/🇦🇺-logo/monash.png',
            'The Australian National University': 'assets/🇦🇺-logo/anu.png',
            'The University of Melbourne': 'assets/🇦🇺-logo/Melbourne.png',
            'The University of Queensland': 'assets/🇦🇺-logo/uq.png',
            'University of New South Wales': 'assets/🇦🇺-logo/unsw.png',
            'University of Western Australia': 'assets/🇦🇺-logo/uwa.png',
            'University of Adelaide': 'assets/🇦🇺-logo/adelaide.png',
            'University of Technology Sydney': 'assets/🇦🇺-logo/uts.png'
        }
    }
};

const randomIDs = ['21BC5229', '22FG8765', '23HI1234', '24JK9876'];

// Legacy arrays for backward compatibility
const randomAddresses = [
            'At- Sadanandpur Dist- Supaul, Bihar',
            '123 Main St, Anytown, USA',
            '456 College Rd, Cityville, State',
            '789 Academic Ave, Metropoli, Country'
];

// Legacy university names array
 const universityNames = [
             'Guru Gobind Singh Indraprastha University',
             'University of Delhi',
             'Jawaharlal Nehru University',
             'Panjab University, Chandigarh',
             'University of Mumbai',
             'Savitribai Phule Pune University',
             'Banaras Hindu University',
             'University of Calcutta',
             'Anna University',
             'University of Hyderabad'
 ];
 const universityWebsites = {
             'Guru Gobind Singh Indraprastha University': 'https://www.ipu.ac.in',
             'University of Delhi': 'https://www.du.ac.in',
             'Jawaharlal Nehru University': 'https://www.jnu.ac.in',
             'Panjab University, Chandigarh': 'https://puchd.ac.in',
             'University of Mumbai': 'https://mu.ac.in',
             'Savitribai Phule Pune University': 'https://www.unipune.ac.in',
             'Banaras Hindu University': 'https://www.bhu.ac.in',
             'University of Calcutta': 'https://www.caluniv.ac.in',
             'Anna University': 'https://www.annauniv.edu',
             'University of Hyderabad': 'https://uohyd.ac.in'
 };
 const universityAddresses = {
             'Guru Gobind Singh Indraprastha University': 'Sector 16C, Dwarka, New Delhi, Delhi 110078',
             'University of Delhi': 'Benito Juarez Marg, South Campus, New Delhi, Delhi 110021',
             'Jawaharlal Nehru University': 'New Mehrauli Road, JNU, New Delhi, Delhi 110067',
             'Panjab University, Chandigarh': 'Sector 14, Chandigarh, 160014',
             'University of Mumbai': 'M.G. Road, Fort, Mumbai, Maharashtra 400032',
             'Savitribai Phule Pune University': 'Ganeshkhind, Pune, Maharashtra 411007',
             'Banaras Hindu University': 'Ajagara, Varanasi, Uttar Pradesh 221005',
             'University of Calcutta': '87/1, College Street, Kolkata, West Bengal 700073',
             'Anna University': 'Sardar Patel Rd, Guindy, Chennai, Tamil Nadu 600025',
             'University of Hyderabad': 'Prof. C.R. Rao Road, Gachibowli, Hyderabad, Telangana 500046'
 };
 // Local university logos from assets/logo/ folder
 const universityLogos = {
             'Guru Gobind Singh Indraprastha University': 'assets/logo/ipu-logo.png',
             'University of Delhi': 'assets/logo/logo-du.png',
             'Jawaharlal Nehru University': 'assets/logo/jnu-logo.png',
             'Panjab University, Chandigarh': 'assets/logo/ipu-logo.png', // Using IPU logo as placeholder
             'University of Mumbai': 'assets/logo/ipu-logo.png', // Using IPU logo as placeholder
             'Savitribai Phule Pune University': 'assets/logo/unipune.ico',
             'Banaras Hindu University': 'assets/logo/bhu-logo.png',
             'University of Calcutta': 'assets/logo/calun-Lgo.png',
             'Anna University': 'assets/logo/ANNAUNIVERSITYLOGO.png',
             'University of Hyderabad': 'assets/logo/UoH-log-new3L.png'
 };
 const universityPrincipals = {
             'Guru Gobind Singh Indraprastha University': 'Prof. Mahesh Verma',
             'University of Delhi': 'Prof. Yogesh Singh',
             'Jawaharlal Nehru University': 'Prof. Santishree Dhulipudi Pandit',
             'Panjab University, Chandigarh': 'Prof. Raj Kumar',
             'University of Mumbai': 'Prof. Suhas Pednekar',
             'Savitribai Phule Pune University': 'Prof. Nitin Karmalkar',
             'Banaras Hindu University': 'Prof. Sudhir Kumar Jain',
             'University of Calcutta': 'Prof. Sonali Chakravarti Banerjee',
             'Anna University': 'Prof. R. Velraj',
             'University of Hyderabad': 'Prof. B.J. Rao'
 };

// Optional defaults per university (ID example, class, email domain)
const universityDefaults = {
            // Indian Universities
            'Guru Gobind Singh Indraprastha University': { id: 'IPU23CSE001', className: 'CSE', emailDomain: 'ipu.ac.in' },
            'University of Delhi': { id: 'DU23CSE001', className: 'CSE', emailDomain: 'du.ac.in' },
            'Jawaharlal Nehru University': { id: 'JNU23CSE001', className: 'CSE', emailDomain: 'jnu.ac.in' },
            'Panjab University, Chandigarh': { id: 'PU23CSE001', className: 'CSE', emailDomain: 'puchd.ac.in' },
            'University of Mumbai': { id: 'MU23ECE001', className: 'ECE', emailDomain: 'mu.ac.in' },
            'Savitribai Phule Pune University': { id: 'SPPU23IT001', className: 'IT', emailDomain: 'unipune.ac.in' },
            'Banaras Hindu University': { id: 'BHU23PHY001', className: 'PHY', emailDomain: 'bhu.ac.in' },
            'University of Calcutta': { id: 'CU23CSE001', className: 'CSE', emailDomain: 'caluniv.ac.in' },
            'Anna University': { id: 'AU23EEE001', className: 'EEE', emailDomain: 'annauniv.edu' },
            'University of Hyderabad': { id: 'UOH23BIO001', className: 'BIO', emailDomain: 'uohyd.ac.in' },

            // Bangladesh Universities (Updated with Google Search Data)
            'University of Dhaka': { id: 'DU23CSE001', className: 'CSE', emailDomain: 'du.ac.bd' },
            'Bangladesh University of Engineering and Technology (BUET)': { id: 'BUET23EEE001', className: 'EEE', emailDomain: 'buet.ac.bd' },
            'Chittagong University of Engineering and Technology (CUET)': { id: 'CUET23CSE001', className: 'CSE', emailDomain: 'cuet.ac.bd' },
            'Rajshahi University of Engineering and Technology (RUET)': { id: 'RUET23ECE001', className: 'ECE', emailDomain: 'ruet.ac.bd' },
            'Khulna University of Engineering and Technology (KUET)': { id: 'KUET23IT001', className: 'IT', emailDomain: 'kuet.ac.bd' },
            'Jahangirnagar University': { id: 'JU23BIO001', className: 'BIO', emailDomain: 'juniv.edu' },
            'Chittagong University': { id: 'CU23PHY001', className: 'PHY', emailDomain: 'cu.ac.bd' },
            'Rajshahi University': { id: 'RU23MTH001', className: 'MTH', emailDomain: 'ru.ac.bd' },
            'Khulna University': { id: 'KU23CHE001', className: 'CHE', emailDomain: 'ku.ac.bd' },
            'Islamic University of Technology (IUT)': { id: 'IUT23CSE001', className: 'CSE', emailDomain: 'iutoic-dhaka.edu' },
            'Bangladesh Agricultural University (BAU)': { id: 'BAU23AGR001', className: 'AGR', emailDomain: 'bau.edu.bd' },
            'Shahjalal University of Science and Technology (SUST)': { id: 'SUST23CSE001', className: 'CSE', emailDomain: 'sust.edu' },
            'Bangladesh University of Professionals (BUP)': { id: 'BUP23BBA001', className: 'BBA', emailDomain: 'bup.edu.bd' },
            'Military Institute of Science and Technology (MIST)': { id: 'MIST23CSE001', className: 'CSE', emailDomain: 'mist.ac.bd' },
            'North South University (NSU)': { id: 'NSU23CSE001', className: 'CSE', emailDomain: 'northsouth.edu' },
            'BRAC University': { id: 'BRAC23CSE001', className: 'CSE', emailDomain: 'bracu.ac.bd' },
            'Independent University Bangladesh (IUB)': { id: 'IUB23CSE001', className: 'CSE', emailDomain: 'iub.edu.bd' },
            'American International University Bangladesh (AIUB)': { id: 'AIUB23CSE001', className: 'CSE', emailDomain: 'aiub.edu' },
        'East West University (EWU)': { id: 'EWU23CSE001', className: 'CSE', emailDomain: 'ewubd.edu' },
        'Daffodil International University (DIU)': { id: 'DIU23CSE001', className: 'CSE', emailDomain: 'daffodilvarsity.edu.bd' },
        'Dhaka International University': { id: 'DIU23CSE001', className: 'CSE', emailDomain: 'students.diu.ac' }
};

// Pakistan university email domains (used if selected university belongs to PK)
Object.assign(universityDefaults, {
    'University of the Punjab': { id: 'PU23CS001', className: 'CSE', emailDomain: 'pu.edu.pk' },
    'National University of Sciences and Technology (NUST)': { id: 'NUST23CS001', className: 'CSE', emailDomain: 'nust.edu.pk' },
    'Quaid-i-Azam University (QAU)': { id: 'QAU23CS001', className: 'CSE', emailDomain: 'qau.edu.pk' },
    'University of Karachi': { id: 'UOK23CS001', className: 'CSE', emailDomain: 'uok.edu.pk' },
    'University of Engineering and Technology, Lahore (UET Lahore)': { id: 'UET23EE001', className: 'EEE', emailDomain: 'uet.edu.pk' },
    'COMSATS University Islamabad': { id: 'CUI23SE001', className: 'SE', emailDomain: 'comsats.edu.pk' },
    'Allama Iqbal Open University (AIOU)': { id: 'AIOU23IT001', className: 'IT', emailDomain: 'aiou.edu.pk' },
    'University of Peshawar': { id: 'UOP23CS001', className: 'CSE', emailDomain: 'uop.edu.pk' },
    'Bahauddin Zakariya University (BZU)': { id: 'BZU23CS001', className: 'CSE', emailDomain: 'bzu.edu.pk' },
    'Government College University, Lahore (GCU Lahore)': { id: 'GCU23CS001', className: 'CSE', emailDomain: 'gcu.edu.pk' },
    'Pakistan Institute of Engineering and Applied Sciences (PIEAS)': { id: 'PIEAS23EE001', className: 'EEE', emailDomain: 'pieas.edu.pk' },
    'National Textile University (NTU)': { id: 'NTU23CE001', className: 'CE', emailDomain: 'ntu.edu.pk' },
    'University of Sargodha (UOS)': { id: 'UOS23CS001', className: 'CSE', emailDomain: 'uos.edu.pk' },
    'Institute of Space Technology (IST)': { id: 'IST23EE001', className: 'EEE', emailDomain: 'ist.edu.pk' },
    'Lahore University of Management Sciences (LUMS)': { id: 'LUMS23CS001', className: 'CSE', emailDomain: 'lums.edu.pk' },
    'Aga Khan University (AKU)': { id: 'AKU23MBBS001', className: 'MBBS', emailDomain: 'aku.edu' },
    'Institute of Business Administration, Karachi (IBA)': { id: 'IBA23BBA001', className: 'BBA', emailDomain: 'iba.edu.pk' },
    'University of Lahore (UOL)': { id: 'UOL23CS001', className: 'CSE', emailDomain: 'uol.edu.pk' },
    'Hamdard University': { id: 'HAMDARD23PHARM001', className: 'PHARM', emailDomain: 'hamdard.edu.pk' },
    'Bahria University': { id: 'BAHRIA23IT001', className: 'IT', emailDomain: 'bahria.edu.pk' },
    'Iqra University': { id: 'IQRA23CS001', className: 'CSE', emailDomain: 'iqra.edu.pk' },
    'Riphah International University': { id: 'RIPHAH23SE001', className: 'SE', emailDomain: 'riphah.edu.pk' },
    'National University of Computer and Emerging Sciences (FAST-NUCES)': { id: 'FAST23CS001', className: 'CSE', emailDomain: 'nu.edu.pk' }
});

// UK university email domains and defaults
Object.assign(universityDefaults, {
    'University of Oxford': { id: 'OXF23CS001', className: 'CSE', emailDomain: 'ox.ac.uk' },
    'University of Cambridge': { id: 'CAM23CS001', className: 'EEE', emailDomain: 'cam.ac.uk' },
    'Imperial College London': { id: 'ICL23CS001', className: 'ECE', emailDomain: 'imperial.ac.uk' },
    'London School of Economics (LSE)': { id: 'LSE23ECO001', className: 'ECO', emailDomain: 'lse.ac.uk' },
    'University College London (UCL)': { id: 'UCL23CS001', className: 'ME', emailDomain: 'ucl.ac.uk' },
    'University of Edinburgh': { id: 'EDU23CS001', className: 'CE', emailDomain: 'ed.ac.uk' },
    'King\'s College London': { id: 'KCL23CS001', className: 'IT', emailDomain: 'kcl.ac.uk' },
    'University of Manchester': { id: 'MAN23CS001', className: 'ICT', emailDomain: 'manchester.ac.uk' },
    'University of Bristol': { id: 'BRI23CS001', className: 'CSE', emailDomain: 'bristol.ac.uk' },
    'University of Glasgow': { id: 'GLA23CS001', className: 'CSE', emailDomain: 'gla.ac.uk' },
    'University of Birmingham': { id: 'BIR23CS001', className: 'CSE', emailDomain: 'birmingham.ac.uk' },
    'University of Leeds': { id: 'LEE23CS001', className: 'CSE', emailDomain: 'leeds.ac.uk' },
    'University of Warwick': { id: 'WAR23CS001', className: 'CSE', emailDomain: 'warwick.ac.uk' },
    'University of Sheffield': { id: 'SHE23CS001', className: 'CSE', emailDomain: 'sheffield.ac.uk' },
    'University of Southampton': { id: 'SOU23CS001', className: 'CSE', emailDomain: 'southampton.ac.uk' },
    'University of York': { id: 'YOR23CS001', className: 'CSE', emailDomain: 'york.ac.uk' },
    'University of Liverpool': { id: 'LIV23CS001', className: 'CSE', emailDomain: 'liverpool.ac.uk' },
    'University of Nottingham': { id: 'NOT23CS001', className: 'CSE', emailDomain: 'nottingham.ac.uk' },
    'University of St Andrews': { id: 'STA23CS001', className: 'CSE', emailDomain: 'st-andrews.ac.uk' },
    'Queen Mary University of London': { id: 'QMUL23CS001', className: 'CSE', emailDomain: 'qmul.ac.uk' },
    'University of the Pacific': { id: 'UOP23CS001', className: 'PHARM', emailDomain: 'pacific.edu' },
    // Nigeria universities
    'University of Ibadan': { id: 'UI23CS001', className: 'CSE', emailDomain: 'ui.edu.ng' },
    'University of Lagos': { id: 'UL23CS001', className: 'EEE', emailDomain: 'unilag.edu.ng' },
    'Obafemi Awolowo University': { id: 'OAU23CS001', className: 'ECE', emailDomain: 'oauife.edu.ng' },
    'Ahmadu Bello University': { id: 'ABU23CS001', className: 'ME', emailDomain: 'abu.edu.ng' },
    'University of Nigeria, Nsukka': { id: 'UNN23CS001', className: 'CE', emailDomain: 'unn.edu.ng' },
    'University of Ilorin': { id: 'UIL23CS001', className: 'IT', emailDomain: 'unilorin.edu.ng' },
    'Federal University of Technology Akure': { id: 'FUTA23CS001', className: 'ICT', emailDomain: 'futa.edu.ng' },
    'University of Benin': { id: 'UB23CS001', className: 'SE', emailDomain: 'uniben.edu' },
    'Covenant University': { id: 'CU23CS001', className: 'AI', emailDomain: 'covenantuniversity.edu.ng' },
    'Lagos State University': { id: 'LASU23CS001', className: 'DS', emailDomain: 'lasu.edu.ng' },
    'University of Jos': { id: 'UJ23CS001', className: 'BBA', emailDomain: 'unijos.edu.ng' },
    'Bayero University Kano': { id: 'BUK23CS001', className: 'MBA', emailDomain: 'buk.edu.ng' },
    'Federal University of Technology Minna': { id: 'FUTM23CS001', className: 'ACC', emailDomain: 'futminna.edu.ng' },
    'University of Port Harcourt': { id: 'UPH23CS001', className: 'FIN', emailDomain: 'uniport.edu.ng' },
    'Nnamdi Azikiwe University': { id: 'NAU23CS001', className: 'MKT', emailDomain: 'unizik.edu.ng' },
    'Adekunle Ajasin University': { id: 'AAU23CS001', className: 'ENG', emailDomain: 'aaua.edu.ng' },
    'University of Agriculture Abeokuta': { id: 'UAA23CS001', className: 'LAW', emailDomain: 'unaab.edu.ng' },
    'Babcock University': { id: 'BU23CS001', className: 'MED', emailDomain: 'babcock.edu.ng' },
    'Redeemer\'s University Nigeria': { id: 'RUN23CS001', className: 'NUR', emailDomain: 'run.edu.ng' },
    'Pan-Atlantic University': { id: 'PAU23CS001', className: 'PHARM', emailDomain: 'pau.edu.ng' },
    // Australia universities
    'The University of Sydney': { id: 'USYD23CS001', className: 'CSE', emailDomain: 'sydney.edu.au' },
    'Monash University': { id: 'MON23CS001', className: 'EEE', emailDomain: 'monash.edu' },
    'The Australian National University': { id: 'ANU23CS001', className: 'ECE', emailDomain: 'anu.edu.au' },
    'The University of Melbourne': { id: 'UMEL23CS001', className: 'ME', emailDomain: 'unimelb.edu.au' },
    'The University of Queensland': { id: 'UQ23CS001', className: 'CE', emailDomain: 'uq.edu.au' },
    'University of New South Wales': { id: 'UNSW23CS001', className: 'IT', emailDomain: 'unsw.edu.au' },
    'University of Western Australia': { id: 'UWA23CS001', className: 'ICT', emailDomain: 'uwa.edu.au' },
    'University of Adelaide': { id: 'UA23CS001', className: 'SE', emailDomain: 'adelaide.edu.au' },
    'University of Technology Sydney': { id: 'UTS23CS001', className: 'AI', emailDomain: 'uts.edu.au' },
    'Curtin University': { id: 'CU23CS001', className: 'DS', emailDomain: 'curtin.edu.au' }
});

const randomPhotos = [
            'assets/photos/01.png',
            'assets/photos/01.png',
            'assets/photos/01.png'
];
const randomLogos = [
            'https://i.ibb.co.com/1G0wV1Z/dummy-logo.png',
            'https://i.ibb.co.com/Z3WqTcm/photo-2025-08-24-12-43-13.jpg',
            'https://i.ibb.co.com/GvTwszKZ/photo-2025-08-24-12-43-09.jpg'
];
const randomSignatures = [
            'https://i.ibb.co.com/M6Lg5tN/dummy-sign.png',
            'https://i.ibb.co.com/s914F7m5/Signature-PNG-Image-HD.png'
];

// Random Name Generation
const indianMaleNames = [
            'Rohan Sharma',
            'Siddharth Patel',
            'Aditya Singh',
            'Arjun Gupta',
            'Dhruv Kumar',
            'Kabir Khan',
            'Aryan Verma',
            'Vihaan Jain',
            'Ishaan Reddy',
            'Dev Joshi',
            'Krishnan Iyer',
            'Neel Mehta',
            'Aarav Das',
            'Vivaan Singh',
            'Reyansh Chaudhary',
            'Samar Arora',
            'Yash Yadav',
            'Kunal Desai',
            'Anand Sharma',
            'Gautam Mishra',
            'Pranav Sen',
            'Rahul Biswas',
            'Abhishek Roy',
            'Ankit Sharma',
             'Manav Choudhury',
             'Kamrul Hossain',
             'Mehul Chowdhury',
             'Mihir Singh',
             'Naveen Kumar',
             'Suman Chakraborty',
             'Harshit Mehta',
             'Anirban Das',
             'Sourav Banerjee',
             'Vikas Sharma',
             'Ritesh Agarwal',
             'Sumit Ghosh',
             'Amitava Sen',
             'Prakash Jha'
];
